name: RMG-Py Unit Test Suite (Push)

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Repositories and Environment
      shell: bash
      run: |
        cd ..
        git clone https://github.com/ReactionMechanismGenerator/RMG-database
        wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH=$HOME/miniconda/bin:$PATH
        cd RMG-Py
        conda env create -q -f environment.yml
        source activate rmg_env
        make

